import type { NextPage } from 'next'
import Head from "next/head";
import { useState } from "react";
import Calendar from "react-calendar";
import "react-calendar/dist/Calendar.css";
import styles from "../styles/Home.module.css";

const formatDate = (date: Date) => {
  return date.toISOString().split("T")[0];
};

const Home: NextPage = () => {
  const [range, setRange] = useState({
    start: "",
    end: "",
  });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Calendar
        onChange={(value: Date[]) => {
          const [start, end] = value;
          setRange({
            start: formatDate(start),
            end: formatDate(end),
          });
          console.log({ start, end });
        }}
        // formatDay={(_locale, d) => {
        //   return formatDate(d);
        // }}
        tileContent={({ activeStartDate, date, view }) =>
          view === "month" && date.getDay() === 0 ? (
            <p className={styles.cell}>It's Sunday!</p>
          ) : (
            <p className={styles.cell}></p>
          )
        }
        selectRange={true}
        minDetail="month"
        value={[new Date(range.start), new Date(range.end)]}
      />
      {JSON.stringify(range, null, 2)}
      {range.start} - {range.end}
    </div>
  );
};

export default Home
